name: lest
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.2.1
  animated_login: ^1.7.0
  convex_bottom_bar: ^3.2.0
  flutter:
    sdk: flutter
  go_router: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
